name: Update Monaco NPM Package

on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  update-monaco:

    runs-on: ubuntu-latest
    
    steps:

      - name: Git Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Git Checkout
        run: |
          dotnet tool install -g Microsoft.Web.LibraryManager.Cli
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21.x
          
      - name: Install latest Monaco Editor via Microsoft LibMan
        run: |
            cd ./source/Monaco
            libman update monaco-editor --destination ./monaco-editor
            
      - name: Extract and format version from loader.js
        id: extract-version
        run: |
            version=$(sed -n 's/.*Version: \([0-9]\+\)\.\([0-9]\+\)\..*/\1.\2/p' source/Monaco/monaco-editor/min/vs/loader.js | tr -d '0' | tr -d '.')
            echo "::set-output name=version::$version"
            
      - name: Check if branch exists
        run: |
          if git rev-parse --verify MONACO-UPDATE-${{ steps.get-version.outputs.version }}; then
            echo "Branch exists"
            export BRANCH_EXISTS=true
          else
            echo "Branch does not exist"
            export BRANCH_EXISTS=false
          fi
      
      - name: Delete Existing Monaco-Branch
        if: env.BRANCH_EXISTS == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete MONACO-UPDATE-${{ steps.get-version.outputs.version }}
      
      - name: Create Monaco-Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git branch MONACO-UPDATE-${{ steps.get-version.outputs.version }}
      
      - name: Push Monaco-Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin MONACO-UPDATE-${{ steps.get-version.outputs.version }}
